version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: justfans-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:5.7
    container_name: justfans-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: justfans
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d


  node:
    image: node:18
    container_name: justfans-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: ["sh", "-c", "npm install && npm run prod"]

volumes:
  db_data:
